name: 编译debug包发布到GitHub Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 配置JDK环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ubuntu设置编译脚本可执行权限
        run: chmod +x ./gradlew
      - name: 编译 Gradle
        run: ./gradlew build
      - name: 编译Debu包
        run: ./gradlew assembleDebug
      - name: 发布到GitHub
        uses: ShaunLWM/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.WANANDROID }} # github 项目secert key 名字必须和设置的一致， 并且token具有相关权限
          APP_FOLDER: app
          RELEASE_TITLE: Version 0.9.9 # 版本名称